# Generated by Django 5.2.8 on 2025-11-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobSearch',
            fields=[
                ('job_id', models.IntegerField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('job_selection', models.CharField(max_length=20)),
                ('alt_description', models.TextField(blank=True, null=True)),
                ('period_end', models.DateField()),
                ('comp_stage', models.CharField(max_length=30)),
                ('practice_id', models.IntegerField()),
            ],
        ),
    ]
