# Generated by Django 5.2.7 on 2025-11-06 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('practice_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('display_name', models.CharField(max_length=50)),
                ('staff_id', models.IntegerField(primary_key=True, serialize=False)),
                ('practice_id', models.IntegerField()),
                ('practice_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_description', models.TextField(blank=True, max_length=100, null=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('practice_id', models.IntegerField()),
                ('job_selection', models.CharField(choices=[('CT_compliance', 'CT compliance'), ('CT_advisory', 'CT advisory'), ('General', 'General'), ('R&D', 'R&D'), ('Tax_audit', 'Tax audit'), ('Tax_DD', 'Tax DD')], max_length=20)),
                ('comp_stage', models.CharField(choices=[('NA', 'N/A'), ('Planning_draft', 'Planning draft'), ('Planning_review', 'Planning review'), ('Comp_draft', 'Comp draft'), ('Comp_review', 'Comp review'), ('Tax_accounting_approved', 'Tax accounting approved'), ('Finalisation_prep', 'Finalisation prep'), ('Finalisation_review', 'Finalisation review'), ('With_Client_for_approval', 'With Client for approval'), ('Approved', 'Approved'), ('Submitted', 'Submitted')], default='NA', max_length=30)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend1app.client')),
                ('partner_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_jobs', to='backend1app.staff')),
                ('preparer_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preparer_jobs', to='backend1app.staff')),
                ('reviewer_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_jobs', to='backend1app.staff')),
                ('task_with_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_with_jobs', to='backend1app.staff')),
            ],
        ),
    ]
