"""
Django settings for backendauth project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv
import os
from celery.schedules import crontab

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent   
env_file_path = BASE_DIR / '.env'          
load_dotenv(dotenv_path=env_file_path)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')   
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ["*"]
URL_FOR_PW = os.getenv("URL_FOR_PW")
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTStatelessUserAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated", 
    ],
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "TOKEN_OBTAIN_SERIALIZER": "backendauthapp.serializers.MyTokenObtainPairSerializer",
    "ALGORITHM": "RS256", 
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "BLACKLIST_APP": True,
    "SIGNING_KEY": os.getenv('SIMPLE_JWT_SIGNING_KEY'),
    "VERIFYING_KEY": os.getenv('SIMPLE_JWT_VERIFYING_KEY'),
}

CELERY_BROKER_URL = "amqp://guest:guest@rabbitmq:5672//"    

CELERY_TASK_ROUTES = {                                       
    'backendauthapp.tasks.*': {'queue': 'backendauth'},        
}

CELERY_BEAT_SCHEDULE = {                                          
    'flush-expired-tokens-daily': {                            
        'task': 'backendauthapp.tasks.flush_expired_tokens_task',     
        'schedule': crontab(hour=23, minute=59),                  
        'options': {'queue': 'backendauth'},                     
    },                                                  

    'flush-blacklisted-access-tokens-daily': {             
        'task': 'backendauthapp.tasks.delete_all_logout_tokens',  
        'schedule': crontab(hour=23, minute=59),             
        'options': {'queue': 'backendauth'},                  
    },                                                        
}                                                                                                                            

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
]

AUTH_USER_MODEL = 'backendauthapp.CustomUser'

# Application definition

INSTALLED_APPS = [
    'daphne',
    'channels',  
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'backendauthapp',
    "rest_framework",
    'rest_framework_simplejwt.token_blacklist',
    'django_rest_passwordreset',
    "django_altcha",
    'django_celery_beat',         
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backendauth.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backendauth.wsgi.application'
ASGI_APPLICATION = 'backendauth.asgi.application'

CHANNEL_LAYERS = {                                       
    "default": {                                       
        "BACKEND": "channels_redis.core.RedisChannelLayer",    
        "CONFIG": {                                      
            "hosts": [("redis", 6379)],                      
        },                                                   
    },                                                      
}  

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': os.getenv('DATABASEAUTH_NAME'),                
        'USER': os.getenv('DATABASEAUTH_USER'),               
        'PASSWORD': os.getenv('DATABASEAUTH_PASSWORD'),         
        'HOST': os.getenv('DATABASEAUTH_HOST'),                  
        'PORT': os.getenv('DATABASEAUTH_PORT'),                  
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/London'

USE_I18N = True

USE_TZ = True

EMAIL_BACKEND = 'backendauth.email_settings.CustomEmailBackend'      
EMAIL_HOST = 'smtp.gmail.com'                                     
EMAIL_PORT = 587                                                     
EMAIL_USE_TLS = True                                                 
DEFAULT_EMAIL = os.getenv("DEFAULT_EMAIL")                        
DEFAULT_FROM_EMAIL = f"WorkVault <{DEFAULT_EMAIL}>"                  
EMAIL_HOST_USER = os.getenv("BAUTH_EMAIL_HOST_USER")              
EMAIL_HOST_PASSWORD = os.getenv("BAUTH_EMAIL_HOST_PASSWORD")        


DJANGO_REST_MULTITOKENAUTH_RESET_TOKEN_EXPIRY_TIME = 1

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

ALTCHA_HMAC_KEY = os.getenv('BAUTH_ALTCHA_HMAC_KEY')
ALTCHA_VERIFICATION_ENABLED = "True"