# Generated by Django 5.2.8 on 2025-11-07 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('date_special', models.CharField(blank=True, max_length=255, null=True)),
                ('link', models.URLField(max_length=500)),
                ('cpd_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('course_type', models.CharField(blank=True, max_length=100, null=True)),
                ('date_scrapy_saved', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
