# Generated by Django 5.2.8 on 2025-11-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend4app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogoutAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=2048)),
                ('logged_out_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
