# Generated by Django 5.2.8 on 2025-11-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('s3_key', models.CharField(max_length=255)),
                ('s3_version_id', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('practice_id', models.IntegerField()),
                ('job_id', models.IntegerField()),
                ('planning_draft_version', models.BooleanField(blank=True, null=True)),
                ('planning_review_version', models.BooleanField(blank=True, null=True)),
                ('comp_draft_version', models.BooleanField(blank=True, null=True)),
                ('comp_review_version', models.BooleanField(blank=True, null=True)),
                ('tax_accounting_approved_version', models.BooleanField(blank=True, null=True)),
                ('finalisation_prep_version', models.BooleanField(blank=True, null=True)),
                ('finalisation_review_version', models.BooleanField(blank=True, null=True)),
                ('with_client_for_approval_version', models.BooleanField(blank=True, null=True)),
                ('approved_version', models.BooleanField(blank=True, null=True)),
                ('submitted_version', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
