upstream appbackend1 {
    server backend1_app:8000;
}

upstream appbackend2 {
    server backend2_app:8001;
}

upstream appbackend3 {
    server backend3_app:8002;
}

upstream appbackend4 {
    server backend4_app:8003;
}

upstream appbackendauth {
    server backendauth_app:7999;
}



server {
    listen 80;
    #listen [::]:80;
    #server_name localhost;

    root /var/www/frontend/;
    location / {
        try_files $uri $uri/ /index.html;
    }
    

    # Proxy REST API calls for backendauth (prefix: /api/)
    location /api/ {
        proxy_pass http://appbackendauth/api/;  # Replace <backendauth_port> with actual port
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        add_header X-Proxy-By "nginx";
    }

    # Proxy REST API calls for backend1 (prefix: /backend1/)
    location /backend1/ {
        proxy_pass http://appbackend1/backend1/;  # Replace <backend1_port> with actual port
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        add_header X-Proxy-By "nginx";
    }

    # Proxy REST API calls for backend2 (prefix: /backend2/)
    location /backend2/ {
        proxy_pass http://appbackend2/backend2/;  # Replace <backend1_port> with actual port
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        add_header X-Proxy-By "nginx";
    }

    # Proxy REST API calls for backend3 (prefix: /backend3/)
    location /backend3/ {
        proxy_pass http://appbackend3/backend3/;  # Replace <backend1_po>  
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        add_header X-Proxy-By "nginx";
    }
 
    # Proxy REST API calls for backend4 (prefix: /backend4/)
    location /backend4/ {
        proxy_pass http://appbackend4/backend4/;  # Replace <backend1_po>
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        add_header X-Proxy-By "nginx";
    }

    # Proxy WebSocket connections (Django Channels)
    location /ws/ {
        proxy_pass http://appbackendauth/ws/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 86400s;
        proxy_send_timeout 86400s;
    }
    
    # Proxy WebSocket connections (Django Channels)
    location /ws/backend1/ {
        proxy_pass http://appbackend1/ws/backend1/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 86400s;
        proxy_send_timeout 86400s;
    }

    
}